# Generated by Django 2.1.7 on 2019-02-16 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190216_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='sales',
            field=models.IntegerField(blank=True, default=20, null=True),
        ),
    ]
