# Generated by Django 2.1.7 on 2019-02-16 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190216_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='sales',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
